baseURL = 'http://opangz.github.io/'
languageCode = 'en-us'
title = 'Owen Pang'

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false